### ISSUE TITLE
Children of MRCA cards doesn't work

### ISSUE THREAD

**Issue by EverSalazar** [wellcaffeinated/Tree-of-Life#10]
When trying to display the children of MRCA cards, nothing happens and no error code is shown.

**Comment by EverSalazar** [comment]
There's something weird going on... It seems that these codes are not pulling the information correctly. For example, in the MLT (MinuteLabs Tree) , hovering over mrcaott2980ott6188 gives the information "MRCA of Eurybia elvina and Lysandra Coridon Gennargenti" but in the OTL, this node is named "Lycaenidae + Riodinidae".

So it seems that MLT is displaying names of species within the branch, while the OTL is displaying the actual names of the direct children (because Lysandra Coridon Gennargenti is part of the Lycaenidae family and Eurybia elvina is part of Riodinidae).

Maybe this is related with the problem of the children not being displayed correctly?

**Comment by EverSalazar** [comment]
So, I think I understand. In MLT, when you hover the card for [mrcaott2980ott6188](http://wellcaffeinated.net/Tree-of-Life/#/?ids=ott67244&ids=ott823917&ids=ott552587&ids=ott823920&ids=ott407108&ids=ott319864&ids=ott449378&ids=mrcaott2980ott6188) you see "MRCA of Eurybia elvina and Lysandra Coridon Gennargenti", which are, respectively ott2980 and ott6188 (thus, mrcaott2980ott6188), but we shouldn't be displaying that, since those two species, for the person navigating the tree, are just two random species within that branch, so the "MRCA of Eurybia elvina and Lysandra Coridon Gennargenti" tag isn't useful. Is it possible to pull a tag like the one in OTL? ("Lycaenidae + Riodinidae")

**Comment by wellcaffeinated** [comment]
Hmmm.. interesting. I thought they were the same but didn't check. I'll try to figure out how they're doing it...

**Comment by EverSalazar** [comment]
This is SO GOOD! The MRCA cards seem to be working now and displaying the correct names in the cards. I still can see a lot of mrca codes in drop down menus, but it has vastly improved and at this point seems good enough for a minimum viable app.

**Comment by EverSalazar** [comment]
Since this issue is solved, I'm closing this and making a new one for the names on the list of parent nodes, which isn't a big deal at this point, in my opinion
