### ISSUE TITLE
Search bar visible at all times

### ISSUE THREAD

**Issue by EverSalazar** [wellcaffeinated/Tree-of-Life#4]
The search bar should be visible at all times, to avoid users having to pan up in order to search for something. Not sure where on the screen it should be, but maybe in a transparent layer on top of everything? (so that it doesn't take too much space)

**Comment by wellcaffeinated** [comment]
@EverSalazar This makes a lot of sense. I can make the bar float at the top. I'm wondering if it should be more compact, and have smaller toggles (like a program toolbar)

**Comment by EverSalazar** [comment]
@wellcaffeinated Awesome. And I'm not super worried about its compactness, but yeah, a bit shorter would be good (and the selector can be shorter too, wide enough to fit "GBIF" and "Wikidata")

**Comment by EverSalazar** [comment]
Now I can see it at all times, though the white thing is too tall. I think that either making it shorter or transparent will do it. But as it is right now, is good enough for minimun viable app, in my opinion.
